import type {
    CatalogoSoporte,
    DefinicionRolSoporte,
    EntradaCatalogoSoporte,
    RolSoporte,
    SensibilidadSoporte,
} from './tipos';

const VERSION = '1.0.4';
const VERIFIED_AT = '2026-07-29';
const OWNER = 'Producto y Soporte Tudojang';
const DEFAULT_ESCALATION = 'Escalar si la pantalla, los permisos o los datos no coinciden con estos pasos.';
const AUTH_UI_ONLY = 'Visibilidad de UI inventariada; autorización backend/reglas no verificada.';

export const ROLES_SOPORTE: Record<RolSoporte, DefinicionRolSoporte> = {
    Admin: { status: 'active', description: 'Administrador del tenant.' },
    Editor: { status: 'active', description: 'Operación académica y comercial.' },
    Asistente: { status: 'active', description: 'Operación diaria con alcance limitado.' },
    Tutor: { status: 'active', description: 'Instructor con acceso técnico y de asistencia.' },
    SuperAdmin: { status: 'active', description: 'Soporte Master entre tenants.' },
    Estudiante: { status: 'reserved', description: 'Rol autenticado futuro; no publica entradas todavía.' },
    Publico: { status: 'active', description: 'Flujos públicos sin rol autenticado.' },
};

export const RUTAS_SOPORTE_CONOCIDAS = [
    '/',
    '/estudiantes',
    '/tienda',
    '/eventos',
    '/notificaciones',
    '/configuracion',
    '/mi-perfil',
    '/renovar-licencia',
    '/aliant-control',
    '/registro-escuela',
    '/login',
    '/inscripcion',
    '/censo/:mionId',
    '/evento/:id',
    '/contrato/:idEstudiante',
    '/firma/:idEstudiante',
    '/firma-imagen/:idEstudiante',
    '/imagen/:idEstudiante',
    '/reportar-pago',
    '/salida',
    '/ayuda',
] as const;

interface EntryOptions {
    sensitivity?: SensibilidadSoporte;
    negativeTerms?: string[];
    authorizationRef?: string;
    escalationReason?: string;
}

const entry = (
    inventoryId: string,
    module: string,
    label: string,
    roles: RolSoporte[],
    route: string,
    aliases: string[],
    actions: string[],
    steps: string[],
    sourceFiles: string[],
    options: EntryOptions = {},
): EntradaCatalogoSoporte => ({
    id: inventoryId,
    inventoryId,
    module,
    label,
    intent: `Orientar sobre ${label.toLowerCase()}.`,
    aliases,
    actions,
    negativeTerms: options.negativeTerms ?? [],
    roles,
    steps,
    route,
    sensitivity: options.sensitivity ?? 'internal',
    escalationReason: options.escalationReason ?? DEFAULT_ESCALATION,
    sourceFiles,
    authorizationRef: options.authorizationRef ?? AUTH_UI_ONLY,
    owner: OWNER,
    introducedIn: VERSION,
    lastVerifiedAt: VERIFIED_AT,
    status: 'active',
});

const A: RolSoporte[] = ['Admin'];
const AE: RolSoporte[] = ['Admin', 'Editor'];
const AEA: RolSoporte[] = ['Admin', 'Editor', 'Asistente'];
const AEAS: RolSoporte[] = ['Admin', 'Editor', 'Asistente', 'SuperAdmin'];
const AUTH: RolSoporte[] = ['Admin', 'Editor', 'Asistente', 'Tutor', 'SuperAdmin'];
const PUBLIC: RolSoporte[] = ['Publico'];

export const CATALOGO_SOPORTE_V1 = {
    schemaVersion: 1,
    catalogVersion: VERSION,
    lastVerifiedAt: VERIFIED_AT,
    roles: ROLES_SOPORTE,
    routes: [...RUTAS_SOPORTE_CONOCIDAS],
    entries: [
        entry('shell.session', 'shell', 'Sesión, navegación y búsqueda global', AUTH, '/',
            ['navegacion principal', 'buscar estudiante', 'cerrar sesion', 'cambiar tema', 'mi perfil'],
            ['navegar', 'buscar', 'cambiar', 'cerrar'],
            ['Usa el menú lateral para abrir un módulo.', 'Usa la búsqueda superior para localizar estudiantes.', 'Abre Mi Perfil o Cerrar Sesión desde la barra lateral.'],
            ['App.tsx']),
        entry('admin.summary', 'administracion', 'Resumen operativo y KPIs', AEAS, '/',
            ['dashboard', 'resumen administrativo', 'indicadores', 'kpis', 'resumen de pagos'],
            ['consultar', 'filtrar', 'revisar'],
            ['Abre Administración.', 'Revisa los indicadores, pagos y eventos del periodo.', 'Ajusta los filtros para cambiar el resumen.'],
            ['vistas/Administracion.tsx', 'vistas/Dashboard.tsx']),
        entry('admin.late-fees', 'administracion', 'Recargos masivos de mora', AEAS, '/',
            ['recargos de mora', 'aplicar recargos', 'mora masiva', 'sobrecargos vencidos'],
            ['aplicar', 'calcular', 'confirmar'],
            ['Abre Administración.', 'Ubica la acción de recargos vencidos.', 'Revisa el alcance antes de confirmar el proceso masivo.'],
            ['vistas/Administracion.tsx'], { sensitivity: 'privileged', authorizationRef: AUTH_UI_ONLY }),
        entry('finance.ledger', 'finanzas', 'Libro de tesorería', AEAS, '/',
            ['libro de tesoreria', 'movimiento financiero', 'ingreso general', 'egreso general', 'csv financiero'],
            ['consultar', 'filtrar', 'registrar', 'editar', 'exportar'],
            ['Abre Administración y entra a Tesorería.', 'Selecciona el libro, la vista diaria o analítica.', 'Filtra o registra el movimiento requerido.'],
            ['vistas/Finanzas.tsx'], { negativeTerms: ['eliminar movimiento', 'borrar movimiento'] }),
        entry('finance.delete', 'finanzas', 'Eliminar movimientos financieros', A, '/',
            ['eliminar movimiento financiero', 'borrar movimiento', 'anular registro financiero'],
            ['eliminar', 'borrar', 'anular'],
            ['Abre Administración > Tesorería.', 'Localiza el movimiento.', 'Usa Eliminar y confirma solo si tu rol y la política vigente lo permiten.'],
            ['vistas/Finanzas.tsx'], { sensitivity: 'privileged', authorizationRef: 'vistas/Finanzas.tsx#RolUsuario.Admin' }),
        entry('finance.student-payments', 'finanzas', 'Pagos y cartera de estudiantes', AEA, '/',
            ['registrar pago', 'pago estudiante', 'cartera', 'deudores', 'notificar deuda', 'pagos'],
            ['registrar', 'consultar', 'notificar'],
            ['Abre Administración > Tesorería y selecciona Pagos.', 'Busca al estudiante.', 'Registra el pago, consulta su cartera o prepara una notificación de deuda.'],
            ['vistas/Finanzas.tsx', 'components/FilaEstudiante.tsx'],
            {
                sensitivity: 'sensitive',
                negativeTerms: [
                    'eliminar movimiento',
                    'borrar movimiento',
                    'pago anual de formulario',
                    'cobro anual de matricula',
                    'cobro anual',
                    'deshacer ultimo pago',
                    'anular ultimo pago',
                    'deshacer pago estudiante',
                    'anular pago estudiante',
                    'revertir pago estudiante',
                ],
            }),
        entry('finance.student-payment-undo', 'finanzas', 'Deshacer o anular el último pago', A, '/',
            [
                'deshacer ultimo pago',
                'anular ultimo pago',
                'revertir ultimo pago',
                'deshacer pago estudiante',
                'anular pago estudiante',
                'revertir pago estudiante',
            ],
            ['deshacer', 'anular', 'revertir'],
            ['Abre Estudiantes y localiza al estudiante.', 'En sus acciones, selecciona Deshacer Último Pago.', 'Confirma la anulación solo si eres Admin y verificaste el pago afectado.'],
            ['components/FilaEstudiante.tsx', 'servicios/pagosApi.ts'],
            {
                sensitivity: 'privileged',
                authorizationRef: 'components/FilaEstudiante.tsx#usuario.rol === RolUsuario.Admin',
            }),
        entry('finance.payment-validation', 'finanzas', 'Validación de comprobantes de pago', AEAS, '/',
            ['validar comprobante', 'aprobar pago reportado', 'rechazar comprobante', 'extraccion de recibo'],
            ['inspeccionar', 'aprobar', 'rechazar', 'emitir'],
            ['Abre la bandeja de validación de pagos.', 'Compara comprobante, extracción y datos del estudiante.', 'Aprueba o rechaza según la evidencia.'],
            ['components/Pagos/PanelValidacionPagos.tsx'], { sensitivity: 'privileged' }),
        entry('agenda.read', 'agenda', 'Consulta de horario semanal', AEAS, '/',
            ['horario semanal', 'agenda de clases', 'carga instructor', 'filtrar horario'],
            ['consultar', 'filtrar', 'revisar'],
            ['Abre Administración > Horarios.', 'Filtra por sede o instructor.', 'Revisa los bloques de la semana.'],
            ['vistas/Horarios.tsx']),
        entry('agenda.manage', 'agenda', 'Gestión de bloques de clase', ['Admin', 'SuperAdmin'], '/',
            ['crear bloque de clase', 'editar horario', 'eliminar clase', 'agendar clase'],
            ['crear', 'editar', 'eliminar', 'agendar'],
            ['Abre Administración > Horarios.', 'Crea o selecciona un bloque.', 'Completa sede, programa, instructor y horario antes de guardar.'],
            ['vistas/Horarios.tsx'], { sensitivity: 'privileged' }),
        entry('students.directory', 'estudiantes', 'Directorio de estudiantes', AEA, '/estudiantes',
            ['buscar estudiante', 'directorio de alumnos', 'ficha tecnica', 'datos de pago estudiante'],
            ['buscar', 'filtrar', 'consultar', 'paginar'],
            ['Abre Estudiantes.', 'Usa búsqueda y filtros.', 'Abre la fila para consultar datos técnicos o de pago.'],
            ['vistas/Estudiantes.tsx', 'components/TablaEstudiantes.tsx'], { sensitivity: 'sensitive' }),
        entry('students.manage', 'estudiantes', 'Crear, editar e importar estudiantes', AEA, '/estudiantes',
            ['agregar estudiante', 'agregar un estudiante', 'crear estudiante', 'nuevo alumno', 'editar estudiante', 'importar estudiantes', 'exportar estudiantes', 'enlace legal estudiante'],
            ['agregar', 'crear', 'editar', 'importar', 'exportar', 'compartir', 'eliminar'],
            ['Abre Estudiantes.', 'Pulsa Agregar Estudiante o selecciona una fila existente.', 'Completa o revisa los datos y pulsa Guardar Estudiante; las acciones destructivas requieren privilegio vigente.'],
            ['vistas/Estudiantes.tsx', 'components/FilaEstudiante.tsx'],
            { sensitivity: 'sensitive', negativeTerms: ['registrar pago', 'marcar asistencia'] }),
        entry('students.kicho', 'estudiantes', 'Censo y aspirantes de Misión KICHO', AE, '/estudiantes',
            ['mision kicho', 'censo kicho', 'aspirantes kicho', 'activar censo'],
            ['activar', 'compartir', 'consultar', 'aprobar', 'rechazar'],
            ['Abre Misión KICHO desde Estudiantes.', 'Activa o comparte el censo.', 'Revisa y decide sobre cada aspirante.'],
            ['vistas/MisionKicho.tsx'], { sensitivity: 'sensitive' }),
        entry('students.kicho-legalize', 'estudiantes', 'Legalización de lote KICHO', A, '/estudiantes',
            ['legalizar lote kicho', 'firmar lote aceptado', 'inyectar censo'],
            ['firmar', 'legalizar', 'inyectar'],
            ['Abre Misión KICHO.', 'Revisa el lote aceptado y su documentación.', 'Firma y legaliza solo con autorización administrativa.'],
            ['vistas/MisionKicho.tsx'], { sensitivity: 'privileged' }),
        entry('students.live-class', 'estudiantes', 'Control de Asistencia y control de salida', ['Admin', 'Editor', 'Asistente', 'Tutor'], '/estudiantes',
            ['control de asistencia', 'asistencia por qr', 'clase en vivo', 'entrada estudiante', 'salida estudiante', 'verificar recogida'],
            ['registrar', 'escanear', 'marcar', 'verificar', 'abrir'],
            ['Abre Control de Asistencia.', 'Escanea el QR o registra la entrada.', 'Marca al estudiante listo y verifica la persona autorizada al entregar.'],
            ['vistas/GestionClase.tsx'], { sensitivity: 'sensitive' }),
        entry('students.certificates', 'estudiantes', 'Certificados individuales y grupales', AEA, '/estudiantes',
            ['generar certificado', 'certificacion', 'diploma', 'certificado grupal'],
            ['buscar', 'generar', 'previsualizar', 'descargar'],
            ['Abre Estudiantes > Certificaciones.', 'Selecciona estudiantes y revisa horas y vista previa.', 'Genera y descarga el PDF.'],
            ['vistas/Certificaciones.tsx']),
        entry('students.cards', 'estudiantes', 'Carnetización e impresión', AE, '/estudiantes',
            ['generar carnet', 'carnetizacion', 'pdf de carnets', 'formato cr80'],
            ['seleccionar', 'generar', 'imprimir', 'marcar', 'solicitar'],
            ['Abre Carnetización.', 'Selecciona formato y estudiantes.', 'Genera el PDF y registra el estado correspondiente.'],
            ['vistas/Carnetizacion.tsx'], { sensitivity: 'sensitive' }),
        entry('store.catalog', 'tienda', 'Catálogo y ventas de tienda', AE, '/tienda',
            ['catalogo tienda', 'vender uniforme', 'asignar compra', 'compartir tienda'],
            ['filtrar', 'compartir', 'vender', 'asignar'],
            ['Abre Tienda.', 'Filtra o selecciona el producto.', 'Comparte el catálogo o asigna la venta al estudiante.'],
            ['vistas/Tienda.tsx']),
        entry('store.inventory', 'tienda', 'Inventario de productos y variantes', A, '/tienda',
            ['crear producto', 'editar implemento', 'eliminar producto', 'variantes de inventario'],
            ['crear', 'editar', 'eliminar', 'administrar'],
            ['Abre Tienda.', 'Entra a la gestión de inventario.', 'Crea o edita producto y variantes; confirma acciones destructivas.'],
            ['vistas/Tienda.tsx'], { sensitivity: 'privileged' }),
        entry('events.catalog', 'eventos', 'Catálogo y enlaces de eventos', AE, '/eventos',
            ['catalogo eventos', 'compartir evento', 'filtrar torneos', 'enlace de inscripcion'],
            ['filtrar', 'consultar', 'compartir'],
            ['Abre Eventos.', 'Filtra o selecciona la actividad.', 'Comparte su enlace público de inscripción.'],
            ['vistas/Eventos.tsx']),
        entry('events.manage', 'eventos', 'Gestión de eventos e inscripciones', A, '/eventos',
            ['crear evento', 'editar torneo', 'eliminar evento', 'aprobar inscripcion evento'],
            ['crear', 'editar', 'eliminar', 'aprobar', 'rechazar'],
            ['Abre Eventos.', 'Crea o selecciona un evento.', 'Gestiona sus datos y solicitudes según tu autorización.'],
            ['vistas/Eventos.tsx', 'components/ModalGestionarSolicitudes.tsx'], { sensitivity: 'privileged' }),
        entry('alerts.payment', 'alertas', 'Recordatorios de deuda y Relay', AE, '/notificaciones',
            ['recordatorio de pago', 'alerta de deuda', 'tudojang relay', 'enviar whatsapp de cartera'],
            ['generar', 'enviar', 'preparar'],
            ['Abre Alertas.', 'Prepara los recordatorios de deuda.', 'Revisa destinatarios y usa el canal manual o Relay disponible.'],
            ['vistas/Notificaciones.tsx'], { sensitivity: 'sensitive' }),
        entry('alerts.history', 'alertas', 'Historial de notificaciones', AE, '/notificaciones',
            ['historial de alertas', 'notificaciones leidas', 'marcar alertas'],
            ['consultar', 'marcar', 'leer'],
            ['Abre Alertas.', 'Revisa el historial.', 'Marca una notificación o todas como leídas.'],
            ['vistas/Notificaciones.tsx']),
        entry('config.identity-payments', 'configuracion', 'Identidad, tarifas y medios de pago', A, '/configuracion',
            ['cambiar logo', 'colores del club', 'datos institucionales', 'mensualidad', 'metodos de pago'],
            ['configurar', 'cambiar', 'editar', 'guardar'],
            ['Abre Configuración.', 'Selecciona identidad, branding o pagos.', 'Actualiza los datos y guarda.'],
            ['vistas/Configuracion.tsx'], { sensitivity: 'privileged', authorizationRef: 'App.tsx#/configuracion requiere RolUsuario.Admin' }),
        entry('config.annual-enrollment-fee', 'configuracion', 'Cobro anual de matrícula o formulario', A, '/configuracion',
            [
                'activar pago anual de formulario',
                'activo pago anual de formulario',
                'activar cobro anual de matricula',
                'cobro anual de matricula',
                'pago anual de formulario',
                'matricula anual',
                'formulario anual',
                'donde marco cobro anual',
            ],
            ['activar', 'marcar', 'establecer', 'guardar'],
            [
                'Abre Configuración > Identidad & Pagos.',
                'Ubica Valor Matrícula / Formulario.',
                'Marca ¿Cobro Anual?, establece el valor y pulsa Guardar Cambios.',
            ],
            ['vistas/Configuracion.tsx'],
            {
                sensitivity: 'privileged',
                negativeTerms: ['registrar pago en tesoreria', 'registrar pago de estudiante'],
                authorizationRef: 'App.tsx#/configuracion requiere RolUsuario.Admin',
            }),
        entry('config.branches', 'configuracion', 'Sedes del dojang', A, '/configuracion',
            ['crear sede', 'editar sede', 'eliminar sede', 'sedes adicionales'],
            ['crear', 'editar', 'eliminar', 'guardar'],
            ['Abre Configuración > Sedes.', 'Crea o selecciona una sede.', 'Guarda respetando el límite del plan.'],
            ['vistas/Configuracion.tsx'], { sensitivity: 'privileged' }),
        entry('config.staff', 'configuracion', 'Equipo técnico, roles y contratos', A, '/configuracion',
            ['equipo tecnico', 'crear usuario', 'editar colaborador', 'retirar personal', 'asignar rol'],
            ['crear', 'editar', 'retirar', 'asignar', 'vincular'],
            ['Abre Configuración > Equipo Técnico.', 'Crea o selecciona el perfil.', 'Define rol, sede y datos contractuales antes de guardar.'],
            ['vistas/Configuracion.tsx'], { sensitivity: 'privileged' }),
        entry('config.programs', 'configuracion', 'Programas y cobros adicionales', A, '/configuracion',
            ['crear programa', 'editar programa', 'eliminar programa', 'cobro adicional'],
            ['crear', 'editar', 'eliminar', 'configurar'],
            ['Abre Configuración > Programas.', 'Crea o selecciona el programa.', 'Configura su tarifa y guarda.'],
            ['vistas/Configuracion.tsx'], { sensitivity: 'privileged' }),
        entry('config.alerts', 'configuracion', 'Preferencias de alertas y push', A, '/configuracion',
            ['configurar alertas', 'notificaciones push', 'preferencias de notificacion'],
            ['activar', 'desactivar', 'configurar', 'guardar'],
            ['Abre Configuración > Alertas.', 'Ajusta el comportamiento de notificaciones y push.', 'Guarda los cambios.'],
            ['vistas/Configuracion.tsx'], { sensitivity: 'privileged' }),
        entry('config.license', 'configuracion', 'Licencia, plan y capacidad', A, '/configuracion',
            ['consultar licencia', 'cambiar plan', 'comprar cupos', 'reiniciar onboarding', 'limites del plan'],
            ['consultar', 'seleccionar', 'comprar', 'reiniciar'],
            ['Abre Configuración > Licencia.', 'Revisa uso y límites.', 'Selecciona plan o capacidad adicional según corresponda.'],
            ['vistas/Configuracion.tsx'], { sensitivity: 'privileged' }),
        entry('profile.self', 'perfil', 'Perfil, contrato y desprendibles', AUTH, '/mi-perfil',
            ['mi perfil', 'mi contrato', 'desprendible de pago', 'datos de usuario'],
            ['consultar', 'abrir', 'descargar'],
            ['Abre Mi Perfil.', 'Revisa identidad, sede, contrato y notificaciones.', 'Abre o descarga el documento disponible.'],
            ['vistas/MiPerfil.tsx'], { sensitivity: 'sensitive' }),
        entry('profile.attendance', 'perfil', 'Horas trabajadas y QR del tutor', ['Asistente', 'Tutor'], '/mi-perfil',
            ['mis horas trabajadas', 'asistencia instructor', 'qr personal tutor'],
            ['consultar', 'abrir', 'escanear'],
            ['Abre Mi Perfil.', 'Consulta las horas trabajadas.', 'Si eres Tutor, abre el escáner QR personal.'],
            ['vistas/MiPerfil.tsx'], { sensitivity: 'sensitive' }),
        entry('license.renew', 'licencia', 'Renovación de licencia suspendida', AUTH, '/renovar-licencia',
            ['licencia suspendida', 'renovar suscripcion', 'pagar licencia', 'contactar soporte licencia'],
            ['consultar', 'renovar', 'pagar', 'contactar'],
            ['Abre Renovar licencia desde el aviso de suspensión.', 'Revisa el estado y la ruta de pago.', 'Usa soporte si el estado no cambia tras el pago.'],
            ['vistas/LicenciaSuspendida.tsx'], { sensitivity: 'sensitive' }),
        entry('master.support', 'master', 'Gestión Master de tickets', ['SuperAdmin'], '/aliant-control',
            ['tickets de soporte', 'resolver caso', 'crear sala de video', 'avanzar etapa soporte'],
            ['consultar', 'avanzar', 'crear', 'resolver'],
            ['Abre Consola Aliant.', 'Selecciona el ticket activo.', 'Actualiza etapa, sala o resolución según el privilegio Master verificado.'],
            ['vistas/MasterDashboard.tsx', 'servicios/soporteApi.ts'],
            { sensitivity: 'privileged', authorizationRef: 'Master email actual; migración pendiente a custom claim SuperAdmin.' }),
        entry('master.tenants', 'master', 'Administración Master de tenants', ['SuperAdmin'], '/aliant-control',
            ['consultar tenants', 'activar suscripcion tenant', 'suspender dojang'],
            ['consultar', 'activar', 'suspender'],
            ['Abre Consola Aliant.', 'Selecciona el tenant.', 'Cambia su estado solo con privilegio Master verificado.'],
            ['vistas/MasterDashboard.tsx'],
            { sensitivity: 'privileged', authorizationRef: 'Master email actual; migración pendiente a custom claim SuperAdmin.' }),
        entry('master.kicho', 'master', 'Operación Master de KICHO', ['SuperAdmin'], '/aliant-control',
            ['crear mision kicho master', 'lotes listos kicho', 'inyectar homologados'],
            ['crear', 'consultar', 'inyectar'],
            ['Abre Consola Aliant > KICHO.', 'Revisa misiones y lotes listos.', 'Ejecuta la operación autorizada.'],
            ['vistas/MasterDashboard.tsx'],
            { sensitivity: 'privileged', authorizationRef: 'Master email actual; migración pendiente a custom claim SuperAdmin.' }),
        entry('master.analytics', 'master', 'Analítica UX y mapa de calor', ['SuperAdmin'], '/aliant-control',
            ['analitica ux', 'mapa de calor', 'limpiar heatmap'],
            ['consultar', 'revisar', 'limpiar'],
            ['Abre Consola Aliant > Analítica.', 'Revisa los datos agregados.', 'Limpia el historial solo si corresponde.'],
            ['vistas/MasterDashboard.tsx'],
            { sensitivity: 'privileged', authorizationRef: 'Master email actual; migración pendiente a custom claim SuperAdmin.' }),
        entry('public.marketing', 'publico', 'Landing y registro de escuela', PUBLIC, '/',
            ['pagina principal', 'registrar escuela', 'activar dojang', 'planes tudojang'],
            ['consultar', 'registrar', 'activar'],
            ['Abre la página principal.', 'Revisa la información o inicia Registrar escuela.', 'Completa el registro y la activación de pago.'],
            ['vistas/PublicLanding.tsx', 'vistas/RegistroEscuela.tsx'],
            { sensitivity: 'public', authorizationRef: 'App.tsx#rutas-publicas' }),
        entry('public.auth', 'publico', 'Inicio de sesión y recuperación', PUBLIC, '/login',
            ['iniciar sesion', 'login', 'recuperar contrasena', 'olvide mi clave'],
            ['ingresar', 'recuperar', 'restablecer'],
            ['Abre Iniciar sesión.', 'Ingresa tus credenciales o pulsa Recuperar contraseña.', 'Sigue el enlace enviado al correo.'],
            ['vistas/Login.tsx', 'components/ModalRecuperarContrasena.tsx'],
            { sensitivity: 'public', authorizationRef: 'App.tsx#/login pública' }),
        entry('public.enrollment', 'publico', 'Inscripción y pago de matrícula', PUBLIC, '/inscripcion',
            ['inscripcion estudiante', 'pagar matricula', 'solicitud de ingreso'],
            ['completar', 'pagar', 'enviar'],
            ['Abre el enlace de inscripción.', 'Completa los datos y legaliza el pago requerido.', 'Envía la solicitud del estudiante.'],
            ['vistas/PasarelaInscripcion.tsx'],
            { sensitivity: 'sensitive', authorizationRef: 'App.tsx#/inscripcion pública con datos mínimos.' }),
        entry('public.census', 'publico', 'Formulario público de censo KICHO', PUBLIC, '/censo/:mionId',
            ['censo publico kicho', 'formulario aspirante', 'datos tutor censo'],
            ['completar', 'enviar', 'registrar'],
            ['Abre el enlace de censo recibido.', 'Completa datos del estudiante, tutor y salud.', 'Revisa y envía el formulario.'],
            ['vistas/CensoPublico.tsx'],
            { sensitivity: 'sensitive', authorizationRef: 'App.tsx#/censo/:mionId pública por enlace.' }),
        entry('public.event', 'publico', 'Inscripción pública a eventos', PUBLIC, '/evento/:id',
            ['ver evento publico', 'inscribirse a torneo', 'registro evento'],
            ['consultar', 'completar', 'enviar'],
            ['Abre el enlace del evento.', 'Revisa datos y condiciones.', 'Completa y envía la inscripción.'],
            ['vistas/EventoPublico.tsx'],
            { sensitivity: 'sensitive', authorizationRef: 'App.tsx#/evento/:id pública.' }),
        entry('public.contract-signature', 'publico', 'Firma de contrato', PUBLIC, '/contrato/:idEstudiante',
            ['firmar contrato', 'contrato estudiante', 'enlace de contrato'],
            ['abrir', 'revisar', 'firmar', 'enviar'],
            ['Abre el enlace de contrato recibido.', 'Revisa el contrato completo.', 'Firma y confirma el envío.'],
            ['vistas/FirmaContrato.tsx'],
            { sensitivity: 'sensitive', authorizationRef: 'App.tsx#/contrato/:idEstudiante pública por enlace.' }),
        entry('public.consent-signature', 'publico', 'Firma de consentimiento de riesgo', PUBLIC, '/firma/:idEstudiante',
            ['firmar consentimiento', 'consentimiento de riesgo', 'enlace de consentimiento'],
            ['abrir', 'revisar', 'firmar', 'enviar'],
            ['Abre el enlace de consentimiento recibido.', 'Revisa el consentimiento de riesgo completo.', 'Firma y confirma el envío.'],
            ['vistas/FirmaConsentimiento.tsx'],
            { sensitivity: 'sensitive', authorizationRef: 'App.tsx#/firma/:idEstudiante pública por enlace.' }),
        entry('public.image-signature', 'publico', 'Firma de autorización de imagen', PUBLIC, '/firma-imagen/:idEstudiante',
            ['firmar autorizacion de imagen', 'autorizacion de imagen', 'consentimiento de imagen'],
            ['abrir', 'revisar', 'firmar', 'enviar'],
            ['Abre el enlace de autorización de imagen recibido.', 'Revisa el documento completo.', 'Firma y confirma el envío.'],
            ['vistas/FirmaImagen.tsx'],
            { sensitivity: 'sensitive', authorizationRef: 'App.tsx#/firma-imagen/:idEstudiante pública por enlace; /imagen/:idEstudiante se conserva como alias legado.' }),
        entry('public.payment-report', 'publico', 'Reporte público de pagos', PUBLIC, '/reportar-pago',
            ['reportar pago', 'subir comprobante', 'buscar estudiante para pago'],
            ['buscar', 'adjuntar', 'reportar', 'enviar'],
            ['Abre Reportar pago.', 'Busca al estudiante con los datos solicitados.', 'Adjunta el comprobante y envía el reporte.'],
            ['vistas/ReportarPagoPublico.tsx'],
            { sensitivity: 'sensitive', authorizationRef: 'App.tsx#/reportar-pago pública con validación posterior.' }),
        entry('public.pickup', 'publico', 'Consulta pública de salida', PUBLIC, '/salida',
            ['consultar salida estudiante', 'monitor de salida', 'recogida por documento'],
            ['consultar', 'buscar', 'verificar'],
            ['Abre la consulta de salida.', 'Ingresa el documento solicitado.', 'Revisa únicamente el estado mostrado.'],
            ['vistas/SalidaPublica.tsx'],
            { sensitivity: 'sensitive', authorizationRef: 'App.tsx#/salida pública; minimizar datos visibles.' }),
        entry('public.help', 'publico', 'Ayuda, FAQ y PQRS', PUBLIC, '/ayuda',
            ['ayuda pqrs', 'preguntas frecuentes', 'buscar ayuda', 'soporte publico'],
            ['buscar', 'consultar', 'orientar'],
            ['Abre Ayuda.', 'Busca por tema o pregunta frecuente.', 'Sigue la orientación o el canal PQRS indicado.'],
            ['vistas/AyudaPqrs.tsx'],
            { sensitivity: 'public', authorizationRef: 'App.tsx#/ayuda pública.' }),
    ],
} satisfies CatalogoSoporte;
